### PR TITLE
Larger torrent infos modal

### PR DESCRIPTION
**Pull request by RoroTiti**
## Description

Regarding the width of today's screens, it appears more comfortable to have a slightly larger torrent info modal.

I think it would be a nice to have UX improvement.

## Related Issue

None.

## Screenshots

From :

https://i.imgur.com/WehobrX.png

To :

https://i.imgur.com/8DR2U5x.png

## Types of changes

UX improvement.

### CODE REVIEW

**Comment by jesec** [comment]
Subjectively speaking, the current ratio looks better than the proposed (too wide) rectangle. 

Nonetheless, I think this is a good idea and I am open to a more modest tweak.

**Comment by RoroTiti** [comment]
Then maybe an intermediary width of 1000px could be enough.

Screenshots : https://i.imgur.com/olr2pjI.png https://i.imgur.com/wN0s1O4.png

**Comment by jesec** [comment]
850px looks like a good choice to me. 15% wider yet not too "rectangle".

To make it wider than that, we would need to tweak other parts of the design as well.

**Comment by RoroTiti** [comment]
Agree on this. If I have time anytime soon, maybe I will make a PR for some more UI changes on this modal to adjust some sizes and proportions. But as of now, thanks for the merge, it's a great improvement yet ! :)

**Comment by agneevX** [comment]
`850px` seems a bit too much, there's too much empty white space on the right:

image

**Pull request merged**
