### PR TITLE
Add role attribute to clickable elements

### PR DESCRIPTION
**Pull request by trailofdead**
Add support for vimium keyboard navigation and screen readers

  * Add menuitem role to SidebarFilter li
  * Add button role to Tooltip div

## Description
Adds `role="menuitem"` to clickable `li` elements in SidebarFilter and `role="button" tabIndex={0}` to `div` elements in Tooltip

## Related Issue
https://github.com/Flood-UI/flood/issues/885

## Screenshots
tooltip
sidebar

## Types of changes

- [ ] Breaking change (changes that break backward compatibility of public API or CLI - semver MAJOR)
- [x] New feature (non-breaking change which adds functionality - semver MINOR)
- [ ] Bug fix (non-breaking change which fixes an issue - semver PATCH)

### CODE REVIEW

**Comment by jesec** [comment]
This change seems to introduce some visual border when the element is focused. It does not align with existing designs.

**Comment by trailofdead** [comment]
The issue you're describing is caused because the div is now focusable, since the addition of the `tabIndex` attribute.  This project uses the eslint jsx-a11y/interactive-supports-focus rule, and removing tabIndex makes the div unfocusable and violates the rule, hurting accessibility.

**Comment by jesec** [comment]
Visual regressions are not preferable, either. I am going to rollback the tabIndex for now unless there is a better solution.

**Comment by trailofdead** [comment]
Can we keep the role attribute, remove tabIndex, and ignore the eslint rule for that line?

**Comment by jesec** [comment]
I fixed the visual regression while preserving the a11y feature with 9f21f943c5c712ad8fdc0049f67d6edcd1bc9854 and 973de1ac6b2a6526d7a8cbe61e7daebf871e55fe.

**Pull request merged**
