### PR TITLE
add support for setting TZ environment variable

### PR DESCRIPTION
**Pull request by onedr0p**
## Description

This allows people at runtime to set an environment variable of `TZ` to their timezone.

## Related Issue

Closes https://github.com/jesec/flood/issues/93

## How Has This Been Tested?

This is a common pattern seen in other projects that utilize docker containers

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jesec** [comment]
May I ask why someone would want to set the timezone?

Flood's server uses UNIX timestamps internally, and, if I remember correctly, server doesn't perform `timestamp to human readable date` conversion.

**Comment by onedr0p** [comment]
This is mostly for having the correct timestamp in the logs. It makes it quicker to debug things and look at the log history.

**Comment by jesec** [comment]
I don't think Flood print human readable dates to logs at the moment. 

Can you give an example about how this would be useful?

**Comment by onedr0p** [comment]
Maybe this is not as helpful as I thought. Sorry

**Comment by jesec** [comment]
It is fine. Thanks for the PR nonetheless.

**Pull request closed without merging**
