### PR TITLE
feat: add select all button on action bar

### PR DESCRIPTION
**Pull request by sabersalv**
## Screenshots

Screen Shot 2021-08-03 at 7 13 05 PM

## Types of changes

- [ ] Breaking change (changes that break backward compatibility of public API or CLI - semver MAJOR)
- [x] New feature (non-breaking change which adds functionality - semver MINOR)
- [ ] Bug fix (non-breaking change which fixes an issue - semver PATCH)

### CODE REVIEW

**Comment by jesec** [comment]
There are too many irrelevant changes...

On a second thought, I do feel that the action bar looks a bit too bloated with an additional button. I don't have a good idea about the alternative at the moment though.

**Comment by sabersalv** [comment]
Rebased, I hide the button on desktop. Will only show on mobile devices, cause mobile lacks of select all.

**Comment by sabersalv** [comment]
Closed until you can find a better design to fit this.

**Comment by jesec** [comment]
Yeah. My primary concern is that the bloated action bar would make an existing issue even worse on mobile devices.

**Pull request closed without merging**
