### PR TITLE
Exatorrent support

### PR DESCRIPTION
**Pull request by Nathan-Kr**
Add support for [exatorrent](https://github.com/varbhat/exatorrent)

Works from version [sha-d2b6fdf](https://github.com/varbhat/exatorrent/pkgs/container/exatorrent/274474518?tag=sha-d2b6fdf)

## Description
supported:
- torrent list
- torrent management (add, start, stop, delete)

not supported:
- settings (no api to tweak settings)
- tags (not supported by exatorrent)
- path change (exatorrent use fixed path)
- priority (not supported by exatorrent)

### CODE REVIEW

**Comment by trim21** [comment]
will you maintain it in the future? I don't use it and I dont' want to add a new client that no one maintaining

**Comment by Nathan-Kr** [comment]
I'll keep it in a fork as I would anyway be the only one using it

**Comment by trim21** [comment]
make sence, also save both time for and code review process.

**Comment by trim21** [comment]
I think you can add your fork to readme about Exatorrent.

https://github.com/jesec/flood?tab=readme-ov-file#supported-clients

**Pull request closed without merging**
