### PR TITLE
fix: flood entrypoint in container images

### PR DESCRIPTION
**Pull request by onedr0p**
## Description

I did not think of the ramifications of moving flood from the entrypoint to the command. Keeping it in the entrypoint should mean it will work the way the documentation expects it too.

Let me know if you want me to move the other flags to the entrypoint as well or if they are expected to be defaults we could leave them out.

 Sorry!

## Types of changes

- [ ] Breaking change (changes that break backward compatibility of public API or CLI - semver MAJOR)
- [ ] New feature (non-breaking change which adds functionality - semver MINOR)
- [ ] Bug fix (non-breaking change which fixes an issue - semver PATCH)

### CODE REVIEW

**Comment by jesec** [comment]
um.. how about the default CLI arguments?

**Comment by onedr0p** [comment]
I see need for --rtorrent but is --host needed? Does/can the app default to 0.0.0.0?

**Comment by jesec** [comment]
It would be insecure if the app listens without limit by default.

**Comment by onedr0p** [comment]
Limit?

**Comment by jesec** [comment]
> Limit?

i.e. 0.0.0.0.

**Comment by jesec** [comment]
I would like to keep all default arguments.

**Comment by onedr0p** [comment]
Ok I'll update soon.

Why isn't `host` set to `0.0.0.0` in the default in flood settings?

**Comment by jesec** [comment]
> Ok I'll update soon.
> 
> Why isn't `host` set to `0.0.0.0` in the default in flood settings?

Security. By listening on `127.0.0.1` by default, Flood is secure by default. It makes sure that Flood doesn’t get exposed to Internet by accident.

**Comment by onedr0p** [comment]
Thanks I understand now. I've updated the PR

I'm curious if you think a entrypoint shell script is worth writing to copy into the container and use in the command part?

e.g.

```sh
....
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/sbin/tini","--"]
CMD ["/entrypoint.sh"]
```

```sh
#!/bin/sh

exec "Do logic here to set default args and append user provided args"

```

**Comment by jesec** [comment]
I would like to move all the flags to entrypoint

> Thanks I understand now. I've updated the PR
> 
> I'm curious if you think I'm the future a entrypoint shell script is worth writing to copy into the container and use in the command part?
> 
> e.g.
> 
> ```shell
> ....
> COPY entrypoint.sh /entrypoint.sh
> ENTRYPOINT ["/sbin/tini","--"]
> CMD ["/entrypoint.sh"]
> ```
> 
> ```shell
> #!/bin/sh
> 
> exec "Do logic here to set default args and append user provided args"
> ```

Not necessary.

**Comment by onedr0p** [comment]
I've updated the PR to add them all.

Maybe I can throw in a feature request for flood to support environment variables? That would help make configuration easier than passing args.

**Comment by jesec** [comment]
> I've updated the PR to add them all to the entrypoint
> 
> Maybe I can throw in a feature request for flood to support environment variables? That would help make configuration easier than passing args.

`FLOOD_OPTION_*`?

**Comment by onedr0p** [comment]
Yes that would be awesome if it's not hard to add!

**Comment by jesec** [comment]
> Yes that would be awesome if it's not hard to add!

Isn’t it already there?

**Comment by onedr0p** [comment]
Sorry I didn't see if any docs on it. Perhaps I'm blind 😅

Why are we passing args to the entrypoint then? We can easily update the examples to show his people can configure this with env rather than args.

**Comment by jesec** [comment]
> Sorry I didn't see any docs on it. Perhaps I'm blind 😅
> 
> Why are we passing args to the entrypoint then? We can easily update the examples to show how people can configure this with env rather than args.

Depends. `docker run -it jesec/flood --some-args` is more convenient than `docker run -it -e FLOOD_OPTION_SOME_ARGS=true jesec/flood`. Though, in a chart or other config file, env may be a better option.

**Comment by onedr0p** [comment]
I think env is the way to go imho, it's makes the dockerfile most compatible across any kind of container deployment methods. Lots of projects out there do it this way and only use args when required.

Currently if I wanted to use env config in Kubernetes it wouldn't be compatible out of the box because the entrypoint is hard coded with those args.

**Comment by jesec** [comment]
> I think env is the way to go imho, it's makes the dockerfile most compatible across any kind of container deployment methods. Lots of projects out there do it this way and only use args when required.
> 
> Currently if I wanted to use env config in Kubernetes it wouldn't be compatible out of the box because the entrypoint is hard coded with those args.

Those default arguments don't need to be overridden. You can use env for others.

**Comment by onedr0p** [comment]
I get that, but why can't they be set as ENV instead of args in the dockerfile? It would make it much easier to work with and look much nicer too!

**Comment by jesec** [comment]
> I get that, but why can't they be set as ENV instead of args in the dockerfile? It would make it much easier to work with and look much nicer too!

I am OK with that. Feel free to change Dockerfile to use ENV for options, then.

**Comment by onedr0p** [comment]
Sounds good, I'll try to update the readme with examples too.

**Pull request merged**
