### PR TITLE
fix rtorrent request queue memory leak

### PR DESCRIPTION
**Pull request by trim21**
## Description

use `p-queue` to queue requests

`p-queue` is a esm only package, so ts-node is replaced with [tsx](https://github.com/esbuild-kit/tsx)

`esbuild-jest` is added to transform esm only packages.

## Related Issue
close https://github.com/jesec/flood/issues/648

## Types of changes

- [ ] Breaking change (changes that break backward compatibility of public API or CLI - semver MAJOR)
- [ ] New feature (non-breaking change which adds functionality - semver MINOR)
- [x] Bug fix (non-breaking change which fixes an issue - semver PATCH)

### CODE REVIEW

**Comment by trim21** [comment]
emmmmm, looks like jest doesn't work with esm only package

**Comment by trim21** [comment]
@jesec

**Comment by jesec** [comment]
This is great! Thank you, @trim21 . One thing I am very happy to see is that this simplified the logics a lot. I do have some wild concerns about introducing esbuild world of tools, but we can handle that later.

**Comment by trim21** [comment]
> This is great! Thank you, @trim21 . One thing I am very happy to see is that this simplified the logics a lot. I do have some wild concerns about introducing esbuild world of tools, but we can handle that later.

what concerns do you have? for example, `tsx` doesn't perform type checking?

**Pull request merged**
